apiVersion: external-secrets.io/v1
kind: ExternalSecret
metadata:
  name: database-secret
  namespace: terraform-platform
spec:
  refreshInterval: 1m

  secretStoreRef:
    name: vault-store
    kind: SecretStore

  target:
    name: database-secret
    creationPolicy: Owner

  data:
    - secretKey: DB_USERNAME
      remoteRef:
        key: platform/database
        property: username

    - secretKey: DB_PASSWORD
      remoteRef:
        key: platform/database
        property: password